// Starting seed list. This is meant to be edited/expanded, not treated as final -
// add or rename institutes here any time and both the API and the frontend
// pick it up automatically. Each institute is just a plain original name - no
// alias list to maintain; search matches substrings of that name directly.

const CORE_INSTITUTES = [
  // ---- IITs (23) ----
  { code: "IITB", name: "IIT Bombay", type: "IIT" },
  { code: "IITD", name: "IIT Delhi", type: "IIT" },
  { code: "IITK", name: "IIT Kanpur", type: "IIT" },
  { code: "IITKGP", name: "IIT Kharagpur", type: "IIT" },
  { code: "IITM", name: "IIT Madras", type: "IIT" },
  { code: "IITR", name: "IIT Roorkee", type: "IIT" },
  { code: "IITG", name: "IIT Guwahati", type: "IIT" },
  { code: "IITH", name: "IIT Hyderabad", type: "IIT" },
  { code: "IITI", name: "IIT Indore", type: "IIT" },
  { code: "IITMANDI", name: "IIT Mandi", type: "IIT" },
  { code: "IITP", name: "IIT Patna", type: "IIT" },
  { code: "IITRPR", name: "IIT Ropar", type: "IIT" },
  { code: "IITBHU", name: "IIT (BHU) Varanasi", type: "IIT" },
  { code: "IITBBS", name: "IIT Bhubaneswar", type: "IIT" },
  { code: "IITGN", name: "IIT Gandhinagar", type: "IIT" },
  { code: "IITJ", name: "IIT Jodhpur", type: "IIT" },
  { code: "IITPKD", name: "IIT Palakkad", type: "IIT" },
  { code: "IITTP", name: "IIT Tirupati", type: "IIT" },
  { code: "IITISM", name: "IIT (ISM) Dhanbad", type: "IIT" },
  { code: "IITBH", name: "IIT Bhilai", type: "IIT" },
  { code: "IITGOA", name: "IIT Goa", type: "IIT" },
  { code: "IITJMU", name: "IIT Jammu", type: "IIT" },
  { code: "IITDH", name: "IIT Dharwad", type: "IIT" },

  // ---- NITs (31) ----
  { code: "NITT", name: "NIT Tiruchirappalli", type: "NIT" },
  { code: "NITW", name: "NIT Warangal", type: "NIT" },
  { code: "NITK", name: "NIT Karnataka Surathkal", type: "NIT" },
  { code: "NITR", name: "NIT Rourkela", type: "NIT" },
  { code: "NITC", name: "NIT Calicut", type: "NIT" },
  { code: "NITDGP", name: "NIT Durgapur", type: "NIT" },
  { code: "NITKKR", name: "NIT Kurukshetra", type: "NIT" },
  { code: "MNIT", name: "NIT Jaipur", type: "NIT" },
  { code: "MNNIT", name: "NIT Allahabad", type: "NIT" },
  { code: "MANIT", name: "NIT Bhopal", type: "NIT" },
  { code: "VNIT", name: "NIT Nagpur", type: "NIT" },
  { code: "NITJ", name: "NIT Jalandhar", type: "NIT" },
  { code: "NITJSR", name: "NIT Jamshedpur", type: "NIT" },
  { code: "NITP", name: "NIT Patna", type: "NIT" },
  { code: "NITRR", name: "NIT Raipur", type: "NIT" },
  { code: "NITSRI", name: "NIT Srinagar", type: "NIT" },
  { code: "NITH", name: "NIT Hamirpur", type: "NIT" },
  { code: "NITS", name: "NIT Silchar", type: "NIT" },
  { code: "NITA", name: "NIT Agartala", type: "NIT" },
  { code: "NITAP", name: "NIT Arunachal Pradesh", type: "NIT" },
  { code: "NITDELHI", name: "NIT Delhi", type: "NIT" },
  { code: "NITGOA", name: "NIT Goa", type: "NIT" },
  { code: "NITMN", name: "NIT Manipur", type: "NIT" },
  { code: "NITM", name: "NIT Meghalaya", type: "NIT" },
  { code: "NITMZ", name: "NIT Mizoram", type: "NIT" },
  { code: "NITNGL", name: "NIT Nagaland", type: "NIT" },
  { code: "NITPY", name: "NIT Puducherry", type: "NIT" },
  { code: "NITSKM", name: "NIT Sikkim", type: "NIT" },
  { code: "NITUK", name: "NIT Uttarakhand", type: "NIT" },
  { code: "NITAP2", name: "NIT Andhra Pradesh", type: "NIT" },
  { code: "SVNIT", name: "NIT Surat", type: "NIT" },

  // ---- IIITs (20) ----
  { code: "IIITH", name: "IIIT Hyderabad", type: "IIIT" },
  { code: "IIITB", name: "IIIT Bangalore", type: "IIIT" },
  { code: "IIITD", name: "IIIT Delhi", type: "IIIT" },
  { code: "IIITA", name: "IIIT Allahabad", type: "IIIT" },
  { code: "ABVIIITM", name: "IIIT Gwalior", type: "IIIT" },
  { code: "IIITDMJ", name: "IIIT Jabalpur", type: "IIIT" },
  { code: "IIITDMK", name: "IIIT Kancheepuram", type: "IIIT" },
  { code: "IIITP", name: "IIIT Pune", type: "IIIT" },
  { code: "IIITN", name: "IIIT Nagpur", type: "IIIT" },
  { code: "IIITK", name: "IIIT Kota", type: "IIIT" },
  { code: "IIITV", name: "IIIT Vadodara", type: "IIIT" },
  { code: "IIITG", name: "IIIT Guwahati", type: "IIIT" },
  { code: "IIITBH", name: "IIIT Bhopal", type: "IIIT" },
  { code: "IIITKL", name: "IIIT Kalyani", type: "IIIT" },
  { code: "IIITR", name: "IIIT Ranchi", type: "IIIT" },
  { code: "IIITSC", name: "IIIT Sri City", type: "IIIT" },
  { code: "IIITU", name: "IIIT Una", type: "IIIT" },
  { code: "IIITS", name: "IIIT Sonepat", type: "IIIT" },
  { code: "IIITL", name: "IIIT Lucknow", type: "IIIT" },
  { code: "IIITKTM", name: "IIIT Kottayam", type: "IIIT" },
];

// ---- Other NIRF-ranked engineering colleges/universities (rank 1-200, 2025) ----
// Only "name" is required; codes below are generated automatically from it.
const OTHER_NAMES = [
  "Techno Main's University, Kolkata",
  "Birla Institute of Technology and Science, Pilani",
  "SRM Institute of Science and Technology",
  "Vellore Institute of Technology",
  "Jadavpur University",
  "Anna University",
  "Siksha O Anusandhan",
  "Amrita Vishwa Vidyapeetham",
  "Jamia Millia Islamia",
  "Thapar Institute of Engineering and Technology",
  "Delhi Technological University",
  "Chandigarh University",
  "Kalasalingam Academy of Research and Education",
  "Aligarh Muslim University",
  "Koneru Lakshmaiah Education Foundation",
  "Kalinga Institute of Industrial Technology",
  "Amity University, Noida",
  "Institute of Chemical Technology, Mumbai",
  "University of Petroleum and Energy Studies",
  "Saveetha Institute of Medical and Technical Sciences",
  "Symbiosis International, Pune",
  "Sri Sivasubramaniya Nadar College of Engineering",
  "Lovely Professional University",
  "Birla Institute of Technology, Ranchi (Mesra)",
  "Graphic Era University",
  "Indian Institute of Engineering Science and Technology, Shibpur",
  "Manipal University Jaipur",
  "Manipal Institute of Technology",
  "Madan Mohan Malaviya University of Technology",
  "Indian Institute of Space Science and Technology",
  "Sathyabama Institute of Science and Technology",
  "PSG College of Technology",
  "Banasthali Vidyapith",
  "University of Hyderabad",
  "M.S. Ramaiah Institute of Technology",
  "Christ University",
  "Rajiv Gandhi Institute of Petroleum Technology",
  "Sant Longowal Institute of Engineering & Technology",
  "Vignan's Foundation for Science, Technology and Research",
  "Jain University, Bengaluru",
  "Vel Tech Rangarajan Dr. Sagunthala R&D Institute",
  "Andhra University College of Engineering",
  "Chitkara University",
  "COEP Technological University, Pune",
  "SR University, Warangal",
  "Defence Institute of Advanced Technology",
  "Panjab University, Chandigarh",
  "Jawaharlal Nehru Technological University, Hyderabad",
  "C.V. Raman Global University",
  "Pandit Deendayal Energy University",
  "Sri Krishna College of Engineering and Technology",
  "Amity University, Kolkata",
  "Amity University Haryana, Gurugram",
  "Anurag University",
  "Vishwakarma Institute of Technology, Pune",
  "Chandigarh Engineering College, Landran, Mohali",
  "Chennai Institute of Technology",
  "Coimbatore Institute of Technology",
  "College of Engineering Trivandrum",
  "MIT World Peace University, Pune",
  "Easwari Engineering College",
  "Galgotias University",
  "Gandhi Institute of Technology and Management (GITAM), Visakhapatnam",
  "Guru Gobind Singh Indraprastha University",
  "Hindustan Institute of Technology and Science",
  "Jawaharlal Nehru Technological University, Kakinada",
  "Jaypee Institute of Information Technology, Noida",
  "Karunya Institute of Technology and Sciences",
  "Kongu Engineering College",
  "KPR Institute of Engineering and Technology",
  "Maharishi Markandeshwar University, Ambala",
  "Mahindra University",
  "Manav Rachna International Institute of Research & Studies",
  "Maulana Azad National Urdu University",
  "National Institute of Food Technology, Entrepreneurship & Management, Sonipat",
  "National Institute of Food Technology, Entrepreneurship and Management, Thanjavur",
  "Nirma University",
  "Nitte Meenakshi Institute of Technology",
  "Noida Institute of Engineering & Technology",
  "PES University",
  "PSG Institute of Technology and Applied Research",
  "Punjab Engineering College, Chandigarh",
  "R.V. College of Engineering",
  "Rajalakshmi Engineering College",
  "Sharda University",
  "Shoolini University",
  "Siddaganga Institute of Technology",
  "SVKM's Narsee Monjee Institute of Management Studies",
  "The Northcap University",
  "Thiagarajar College of Engineering",
  "University College of Engineering, Osmania University",
  "University of Allahabad",
  "Veermata Jijabai Technological Institute, Mumbai",
  "Amity University Rajasthan, Jaipur",
  "B.S. Abdur Rahman Crescent Institute of Science and Technology",
  "B.M.S. College of Engineering",
  "Bharati Vidyapeeth College of Engineering, Pune",
  "CMR Institute of Technology",
  "CGC College of Engineering, Landran",
  "Chaitanya Bharathi Institute of Technology",
  "CVR College of Engineering",
  "Dayalbagh Educational Institute",
  "Dr. D. Y. Patil Institute of Technology",
  "Dr. M. G. R. Educational and Research Institute",
  "G. L. A. University, Mathura",
  "G.L. Bajaj Institute of Technology and Management",
  "Gokaraju Rangaraju Institute of Engineering & Technology",
  "Guru Ghasidas Vishwavidyalaya",
  "Institute of Aeronautical Engineering",
  "Institute of Engineering & Management, Kolkata",
  "Integral University",
  "Islamic University of Science & Technology, Pulwama",
  "J. C. Bose University of Science and Technology, YMCA",
  "Jawaharlal Nehru Technological University, Anantapur",
  "JSPM's Rajarshi Shahu College of Engineering",
  "KIET Group of Institutions",
  "KLE Technological University",
  "Kumaraguru College of Technology",
  "Maulana Abul Kalam Azad University of Technology",
  "Mepco Schlenk Engineering College",
  "New Horizon College of Engineering",
  "NMAM Institute of Technology",
  "North Eastern Regional Institute of Science & Technology",
  "R.M.K. Engineering College",
  "Ramdeobaba University, Nagpur",
  "Shri Mata Vaishno Devi University",
  "Sona College of Technology",
  "Sri Ramakrishna Engineering College",
  "Sri Sai Ram Institute of Technology",
  "Sri Sairam Engineering College",
  "Tezpur University",
  "The National Institute of Engineering, Mysuru",
  "Vallurupalli Nageswara Rao Vignana Jyothi Institute of Engineering and Technology",
  "Vardhaman College of Engineering",
  "Veer Surendra Sai University of Technology",
  "Velagapudi Ramakrishna Siddhartha Engineering College",
  "Vels Institute of Science Technology and Advanced Studies",
  "Vignan Institute of Technology and Science",
  "Visvesvaraya Technological University",
  "Yeshwantrao Chavan College of Engineering",
  "Netaji Subhas University of Technology",
];

function slugify(name) {
  return name.toUpperCase().replace(/[^A-Z0-9]+/g, "_").replace(/^_+|_+$/g, "").slice(0, 40);
}

const OTHER_INSTITUTES = OTHER_NAMES.map((name, i) => ({
  code: `OTH_${slugify(name)}_${i}`,
  name,
  type: "Other",
}));

const INSTITUTES = [...CORE_INSTITUTES, ...OTHER_INSTITUTES];

const BRANCHES = [
  "Computer Science Engineering",
  "Electronics & Communication Engineering",
  "Electrical Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Chemical Engineering",
  "Metallurgical & Materials Engineering",
  "Aerospace Engineering",
  "Biotechnology",
  "Mathematics & Computing",
  "Engineering Physics",
  "Industrial & Production Engineering",
];

const EXAM_TYPES = ["Mid Semester", "End Semester"];

const SEMESTERS = [1, 2, 3, 4, 5, 6, 7, 8];

module.exports = { INSTITUTES, BRANCHES, EXAM_TYPES, SEMESTERS };
